version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: zemljaslova-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - zemljaslova-network

  zemljaslova-subscriber:
    build:
      context: .
      dockerfile: ./ZemljaSlova.Subscriber/Dockerfile
    container_name: zemljaslova-subscriber
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=zemljaslova@gmail.com
      - SMTP_PASSWORD=vimi rwyf uoqq mjvt
    depends_on:
      - rabbitmq
    networks:
      - zemljaslova-network
    restart: unless-stopped

volumes:
  rabbitmq_data:

networks:
  zemljaslova-network:
    driver: bridge
